#!/usr/bin/python
#
# Open all files in vim that is connected to socket server.

import os
import sys
from subprocess import call

if __name__ == "__main__":

   script_name = "/vim-client.py"
   script_path = os.environ.get("MD_ENV_SCRIPT_PATH")
   if script_path is None:
      print("MD_ENV_SCRIPT_PATH environment variable not defined")
      sys.exit(1)

   files = sys.argv[1:]
   for file in files:
      call(["python", script_path + script_name, "ex", "tabe " + os.path.abspath(file)])

   call(["python", script_path + script_name, "redraw", ""])
